name: ilovebandits-ci-pipeline

on:
  pull_request:
    branches:
      - main
    paths-ignore:
    - docs/**
    - README.md

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.10"
            tox-env: py310
          - os: ubuntu-latest
            python-version: "3.11"
            tox-env: py311
          # - os: windows-latest
          #   python-version: "3.10"
          #   tox-env: py310
          # - os: windows-latest
          #   python-version: "3.11"
          #   tox-env: py311
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        path: /tmp/.uv-cache
        key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          uv-${{ runner.os }}

    - name: Install Tox and Tox-uv
      run: uv tool install tox --with tox-uv

    - name: Run Pytests via Tox
      run: uv run tox -e ${{ matrix.tox-env }}